
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
http:
  # Cloudflare setting to unlock reverse proxy
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.68.0/24
